services:
  - type: web
    name: chat-sdk
    runtime: java17  # use java or java17
    plan: free
    runtime: openjdk21  # Updated to Java 21
    plan: free  # Explicitly use free tier
    branch: main
    repo: https://github.com/sanjeetji/ChatSdk
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/Chat-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
      - key: SPRING_DATASOURCE_URL
        sync: false  # Set in Render dashboard if your app uses a database
    autoDeploy: true
