services:
  - type: web
    name: chat-sdk
    env: java
    plan: free
    branch: main
    repo: https://github.com/sanjeetji/ChatSdk
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/Chat-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
    autoDeploy: true
