services:
  - type: web
    name: chat-sdk
    env: java # Use 'java' as the environment, not runtime
    plan: free
    branch: main
    repo: https://github.com/sanjeetji/ChatSdk
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/Chat-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: "17" # Specify the Java version (e.g., 17, 21, etc.)
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
      - key: SPRING_DATASOURCE_URL
        sync: false
    autoDeploy: true
