services:
  - type: web
    name: chat-sdk
    env: docker
    plan: free
    branch: main
    repo: https://github.com/sanjeetji/ChatSdk
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
    autoDeploy: true