    services:
      - type: web
        name: chat-sdk
        env: java
        branch: main
        repo: https://github.com/sanjeetji/ChatSdk
        buildCommand: ./mvnw clean package -DskipTests
        startCommand: java -jar target/chatSdk-0.0.1-SNAPSHOT.jar
        envVars:
          - key: JAVA_OPTS
            value: "-Xms256m -Xmx512m"
          - key: SPRING_DATASOURCE_URL
            sync: false  # Set in Render dashboard for security
        autoDeploy: true